# Generated by Django 4.2 on 2023-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgehog',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
